### ISSUE TITLE
Error 500 - Redirections

### ISSUE THREAD

**Issue by DevWebBA** [alma/alma-installments-prestashop#357]
In version 3.2, when you try to pay for an order in 10 or 12 instalments, a 500 error is triggered on the redirection url.

After checking, this line needs to be adjusted in : lib/Model/PaymentData.php (l264)

```
if ($feePlans['installmentsCount'] > 4) {
    // Failed : $dataPayment['payment']['cart'] = $this->cartInfo($cart);
    $dataPayment['payment']['cart'] = $this->cartData->cartInfo($cart);
}
```

Logs PHP

```
[error] 113926#113926: *6385146 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method Alma\PrestaShop\Model\PaymentData::cartInfo() in /var/www/prod/public/modules/alma/lib/Model/PaymentData.php:264
Stack trace:
#0 /var/www/prod/public/modules/alma/controllers/front/payment.php(126): Alma\PrestaShop\Model\PaymentData->dataFromCart(Object(Cart), Object(Context), Array, true)
#1 /var/www/prod/public/classes/controller/Controller.php(281): AlmaPaymentModuleFrontController->postProcess()
#2 /var/www/prod/public/classes/Dispatcher.php(515): ControllerCore->run()
#3 /var/www/prod/public/index.php(28): DispatcherCore->dispatch()
#4 {main}
  thrown in /var/www/prod/public/modules/alma/lib/Model/PaymentData.php on line 264
```

**Comment by Benjamin-Freoua-Alma** [comment]
Hello @DevWebBA 
Thank you for your issue.
We just publish a release in version 3.2.1 to fix it in Github and in a few hour it will be publish in the marketplace Prestashop.
Have a good day
